# -- Main Menu --
# Displayed in the header, ordered by weight (lowest first).

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Writing"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40


# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
